### ISSUE TITLE
invalid choice

### ISSUE THREAD

**Issue by 7h3pr0xy** [Viralmaniar/Powershell-RAT#1]
[+] All good....

1. Set Execution Po
2. Take screen shot
3. Schedule a task
4. Extract data via
5. Schedule a task
6. Delete screen sh
7. Schedule a task
8. Hail Mary: Quick
9. Exit
2
[!] Invalid Choice

it says invalid choice

**Comment by tr3x85** [comment]
Hi,

I faced the same error message too.

Thanks

**Comment by tr3x85** [comment]
U have to use powershell version 3 onwards.
