### ISSUE TITLE
Actually not FUD (WIN 10)

### ISSUE THREAD

**Issue by pctripsesp** [Viralmaniar/Powershell-RAT#2]
Windows Defender detects bat file execution "invalid digital signature"
![fail_bat](https://user-images.githubusercontent.com/17095580/37610199-456e7a2c-2b9f-11e8-90f0-35394aa3e780.png)

**Comment by Viralmaniar** [comment]
@pctripsesp Do not run Shoot.bat directly. Run it from Python.
